@extends('layouts.basic')

@section('title', 'Home')

@section('content')
    <h2 class="text-danger text-center m-3">The Manager page's view</h2>
    <div class="container">
        <div class="row gy-4">
            <div class="col-sm">
                <a href="{{ route('customer.index') }}">
                    <div class="card h-100" "> <img src="https://media.licdn.com/dms/image/C5612AQEXTt4grfiTxQ/article-cover_image-shrink_720_1280/0/1520181045312?e=2147483647&v=beta&t=Z6g_nFW524kw9hTrqMfS9CshPF4-VV4OffMyJmROOCI"
                                                                                                                                                                                                                    class="card-img-top" alt="Customers photo"></a>
                                                                                                                                                                                                                <div class="card-body">
                                                                                                                                                                                                                    <h5 class="card-title fw-bold">Customers</h5>
                                                                                                                                                                                                                    <p class="card-text">Suppose to validate or not validate the new customers creation requestes made by the employees
                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                <div class="progress" role="progressbar" aria-label="Animated striped example" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100">
                                                                                                                                                                                                                    <div class="progress-bar progress-bar-striped progress-bar-animated" style="width: 95%">this section is completed</div>
                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                            </div>
                                                                                                                                                                                                        </div>
                                                                                                                                                                                                  
                                                                                                                                                                                                       
                                                                                                                                                                                                                <div class="col-sm">
                                                                                                                                                                                                                    <a href="#">
                                                                                                                                                                                                                    <div class="card h-100">
                                                                                                                                                                                                                        <img src="https://img.supplychainconnect.com/files/base/ebm/sourcetoday/image/2019/06/sourcetoday_2879_gettyimages_650017844.png?auto=format,compress&fit=fill&fill=blur&w=1200&h=630"
                                                                                                                                                                                                                            class="card-img-top" alt="Suppliers photo">
                                                                                                                                                                                                                        <div class="card-body"></a>
                                                                                                                                                                                                                            <h5 class="card-title fw-bold">Suppliers</h5>
                                                                                                                                                                                                                            <p class="card-text">Suppose to validate or not validate the new suppliers creation requestes made by the employees</p>
                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                        
                                                                                                                                                                                                                        <div class="progress" role="progressbar" aria-label="Animated striped example" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100">
                                                                                                                                                                                                                            <div class="progress-bar progress-bar-striped progress-bar-animated" style="width: 5%"></div>
                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                <div class="col-sm">
                                                                                                                                                                                                                    <a href="{{ route('vacation.index') }}">
                                                                                                                                                                                                                    <div class="card h-100">
                                                                                                                                                                                                                        <img src="https://previews.123rf.com/images/rawpixel/rawpixel1802/rawpixel180200347/94660584-vacation-calendar-reminder.jpg"
                                                                                                                                                                                                                            class="card-img-top" alt="Vacation photo">
                                                                                                                                                                                                                        <div class="card-body"></a>
                                                                                                                                                                                                                            <a href="{{ route('leave.index') }}">
                                                                                                                                                                                                                            <h5 class="card-title fw-bold">Vacation</h5></a>
                                                                                                                                                                                                                            <p class="card-text">Suppose to validate or not validate the vacation requests requestes made by the employees</p>
                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                        <div class="progress" role="progressbar" aria-label="Animated striped example" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100">
                                                                                                                                                                                                                            <div class="progress-bar progress-bar-striped progress-bar-animated" style="width: 75%">this section is under construction</div>
                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                </div>
                                                                                                                                                                                                            </div>
                                                                                                                                                                                                        </div>
@endsection
